events = [("Epeiste", "choice", ("Parler", "S\'évader", "Se battre")),
          ("Amazones", "choice", ("Parler", "S\'évader", "Se battre")),
          ("Nain", "pre", ("Le nain est seul", "Le nain est seul", "Le nain est seul", "1:friends:5:force:6:endurance:12:richesse",
                           "3:friends:5:force:6:endurance:12:richesse",
                           "5:friends:5:force:6:endurance:12:richesse"), "choice", ("Parler", "S\'évader", "Se battre")),
          ("Elfe", "pre",
           ("Rien ne se passe.", "Il est le leader d'une bande d'elfes.", "C'est un magicien avec une bombe à gaz.",
            "1:friends:3:force:3:endurance:2:richesse",
            "C'est un prêtre d'un culte de la forêt qui possède une potion de soin",
            "1:friends:4:force:4:endurance:7:richesse"),
           "choice", ("Parler", "S\'évader", "Se battre")),
          ("Semi-Homme", "pre",
           ("Conversation banale. C'est une perte de temps.", "Le semi-homme vous indique la position de son village.",
            "Rien ne se passe.", "Rien ne se passe.", "Rien ne se passe.", "Rien ne se passe.")),
          ("Rencontre magicien", "approche", ("Le magicien vous rejoint dans votre quête",
                                              "-5:vie:all:destroy")),
          ("Magicien", "choice", ("Parler", "S\'évader", "Se battre")),
          ("Tombe", "redirect", ("Momie", "Piller la tombe", "Fantômes", "Colère des guerriers", "Spectre de la tombe",
                                 "Dangers et trésors")),
          ("Gobelins", "choice", ("S\'évader", "Se battre")),
          ("Cache gobeline", "choice", ("S\'évader", "Se battre")),
          ("Orcs", "choice", ("S\'évader", "Se battre")),
          ("Nains", "choice", ("Parler", "S\'évader", "Se battre")),
          ("Mercenaires", "choice", ("Parler", "S\'évader", "Se battre")),
          ("Ruines", "choice", ("Rechercher", "S\'évader")),
          ("Petite tempête", "choice", ("S\'évader","")),
          ("Maison de magicien", "redirect", (
              "Magicien", "Magicien", "Attaque de Magicien", "Rencontre magicien", "Tour de magicien",
              "Tour de magicien")),
          ("Mésaventure", "condition", ("Avoir cheval", "Perte du cheval")),
          ("Pluie", "boucle", ("pluie", "-1:vie")),
          ("Passe haut", "pre", (
              "Rien ne se passe", "Rien ne se passe", "Rien ne se passe", "Rien ne se passe", "Rien ne se passe",
              "Rien ne se passe", "Rien ne se passe", "All:-1",
              "Tout le monde perd 2 de vie et les montures meurent",
              "Tout le monde perd 3 de vie et les montures meurent",
              "Tout le monde perd 4 de vie et les montures meurent",
              "Tout le monde perd 4 de vie et les montures meurent",)),
          ("Chute de pierre", "pre", (
              "Les pierres vous passent à côté", "Les pierres vous passent à côté", "Les pierres vous passent à côté",
              "Les pierres vous passent à côté", "Vie:-1", "Vie:-6")),
          ("Rocher", "choice", ("S\'évader", "Se battre")),
          ("Griffon", "choice", ("Parler", "S\'évader", "Se battre")),
          ("Harpie", "choice", ("Parler", "S\'évader", "Se battre")),
          ("Géant", "choice", ("Parler", "S\'évader", "Se battre")),
          ("Risques", "condition", ("Avoir cheval", "Perte du cheval")),
          ("Mines des nains", "choice", ("Se reposer", "Se nourrir", "S\'évader")),
          ("Temple secret", "choice", ("Se reposer", "Se nourrir", "S\'évader")),
          ("Ville cachée", "choice", ("Se reposer", "Se nourrir", "S\'évader")),
          ("Mines abandonnées", "redirect", ("Mines des nains", "Bandits", "Passage sombre", "Arche de voyage", "Cave", "Cave")),
          ("Passage étroit", "condition", ("Avoir une équipe", "Perte de l'équipe"))
          ]

perso_carac = [("Epeiste", 15, "richesse"),
               ("Amazones", 15, "richesse"),
               ("Nain", 15, "richesse"),
               ("Elfe", 15, "richesse"),
               ("Magicien", 15, "richesse"),
               ("Gobelins", 15, "richesse"),
               ("Cache gobeline", 15, "richesse"),
               ("Orcs", -15, "vie"),
               ("Nains", 15, "richesse"),
               ("Mercenaires", 15, "richesse"),
               ("Ruines", 15, "richesse"),
               ("Rocher", 15, "richesse"),
               ("Griffon", 15, "richesse"),
               ("Harpie", 15, "richesse"),
               ("Géant", -15, "vie"),
               ("Mines des nains", 5, "nourriture"),
               ("Temple secret", 5, "nourriture"),
               ("Ville cachée", 5, "nourriture")
               ]

event_mountain = [((1, 1), 'Epeiste'), ((1, 2), 'Rocher'), ((1, 3), 'Tombe'), ((1, 4), 'Mésaventure'),
                  ((1, 5), 'Passage étroit'),
                  ((1, 6), 'Géant'),
                  ((2, 1), 'Mercenaires'), ((2, 2), 'Griffon'), ((2, 3), 'Tombe'), ((2, 4), 'Mésaventure'),
                  ((2, 5), 'Passage étroit'),
                  ((2, 6), 'Gobelins'),
                  ((3, 1), 'Amazones'), ((3, 2), 'Magicien'), ((3, 3), 'Nains'), ((3, 4), 'Pluie'),
                  ((3, 5), 'Passe haut'),
                  ((3, 6), 'Mines des nains'),
                  ((4, 1), 'Nain'), ((4, 2), 'Maison de magicien'), ((4, 3), 'Orcs'), ((4, 4), 'Pluie'),
                  ((4, 5), 'Passe haut'),
                  ((4, 6), 'Mines abandonnées'),
                  ((5, 1), 'Elfe'), ((5, 2), 'Harpie'), ((5, 3), 'Gobelins'), ((5, 4), 'Chute de pierre'),
                  ((5, 5), 'Passe haut'),
                  ((5, 6), 'Temple secret'),
                  ((6, 1), 'Semi-Homme'), ((6, 2), 'Petite tempête'), ((6, 3), 'Cache gobeline'),
                  ((6, 4), 'Ville cachée'), ((6, 5), 'Risques'), ((6, 6), 'Ruines')]

event_road = [((1, 1), 'Prêtre'), ((1, 2), 'Police locale'), ((1, 3), 'Mercenaires'), ((1, 4), 'Elfe'),
              ((1, 5), 'Menestrel itinérant'), ((1, 6), 'Mésaventure'),
              ((2, 1), 'Moines'), ((2, 2), 'Bandits'), ((2, 3), 'Mercenaires'), ((2, 4), 'Elfe'),
              ((2, 5), 'Fugitif'), ((2, 6), 'Mésaventure'),
              ((3, 1), 'Magicien'), ((3, 2), 'Bandits'), ((3, 3), 'Amazones'), ((3, 4), 'Troll'),
              ((3, 5), 'Patrouille montée'), ((3, 6), 'Pluie'),
              ((4, 1), 'Sorcière'), ((4, 2), 'Bandits'), ((4, 3), 'Nains'), ((4, 4), 'Rencontre avec un seigneur'),
              ((4, 5), 'Marchand'), ((4, 6), 'Pluie'),
              ((5, 1), 'Ferme'), ((5, 2), 'Epeiste'), ((5, 3), 'Nain'), ((5, 4), 'Marchand'),
              ((5, 5), 'Caravane de marchand'),
              ((5, 6), 'Marchand'),
              ((6, 1), 'Ferme'), ((6, 2), 'Epeiste'), ((6, 3), 'Semi-Homme'),
              ((6, 4), 'Marchand'), ((6, 5), 'Caravane de marchand'),
              ((6, 6), 'Caravane de marchand')]

event_river = [((1, 1), 'Epeiste'), ((1, 2), 'Equipage du radeau'), ((1, 3), 'Chevalier du pont'),
               ((1, 4), 'Crocodiles'),
               ((1, 5), 'Attaque de sanglier'), ((1, 6), 'Equipage du radeau'),
               ((2, 1), 'Mercenaires'), ((2, 2), 'Equipage du radeau'), ((2, 3), 'Chevalier du pont'),
               ((2, 4), 'Crocodiles'), ((2, 5), 'Chat de chasse'), ((2, 6), 'Equipage du radeau'),
               ((3, 1), 'Amazones'), ((3, 2), 'Equipage du radeau'), ((3, 3), 'Troll'), ((3, 4), 'Serpent'),
               ((3, 5), 'Cheveaux sauvages'), ((3, 6), 'Equipage du radeau'),
               ((4, 1), 'Nain'), ((4, 2), 'Ferme'), ((4, 3), 'Troll'), ((4, 4), 'Serpent'),
               ((4, 5), 'Radeau'), ((4, 6), 'Radeau qui chavire'),
               ((5, 1), 'Elfe'), ((5, 2), 'Bandits'), ((5, 3), 'Gobelins'), ((5, 4), 'Loups'),
               ((5, 5), 'Radeau'), ((5, 6), 'Radeau pris dans le courant'),
               ((6, 1), 'Semi-Homme'), ((6, 2), 'Araignées'), ((6, 3), 'Orcs'),
               ((6, 4), 'Ours'), ((6, 5), 'Radeau'),
               ((6, 6), 'Radeau en eau agitée')]

event_country = [((1, 1), 'Epeiste'), ((1, 2), 'Ferme'), ((1, 3), 'Gobelins'), ((1, 4), 'Cheveaux sauvages'),
                 ((1, 5), 'Haut Altar'),
                 ((1, 6), 'Mésaventure'),
                 ((2, 1), 'Mercenaires'), ((2, 2), 'Ferme'), ((2, 3), 'Orcs'), ((2, 4), 'Loups'),
                 ((2, 5), 'Passage sombre'),
                 ((2, 6), 'Mésaventure'),
                 ((3, 1), 'Amazones'), ((3, 2), 'Police locale'), ((3, 3), 'Troll'), ((3, 4), 'Loups'),
                 ((3, 5), 'Mines abandonnées'),
                 ((3, 6), 'Mésaventure'),
                 ((4, 1), 'Nain'), ((4, 2), 'Prêtre'), ((4, 3), 'Bandits'), ((4, 4), 'Loups'),
                 ((4, 5), 'Ruines'),
                 ((4, 6), 'Mésaventure'),
                 ((5, 1), 'Elfe'), ((5, 2), 'Moines'), ((5, 3), 'Cache gobeline'), ((5, 4), 'Chat de chasse'),
                 ((5, 5), 'Maison de magicien'),
                 ((5, 6), 'Pluie'),
                 ((6, 1), 'Semi-Homme'), ((6, 2), 'Magicien'), ((6, 3), 'Gobelins'),
                 ((6, 4), 'Patrouille montée'), ((6, 5), 'Guerrier blessé'),
                 ((6, 6), 'Chat de chasse')]

event_desert = [((1, 1), 'Moines'), ((1, 2), 'Cave'), ((1, 3), 'Amazones'), ((1, 4), 'Spectre de la tombe'),
                ((1, 5), 'Ruines'),
                ((1, 6), 'Mésaventure'),
                ((2, 1), 'Caravane de marchand'), ((2, 2), 'Spectre'), ((2, 3), 'Faim'), ((2, 4), 'Lézard géant'),
                ((2, 5), 'Ruines'),
                ((2, 6), 'Mésaventure'),
                ((3, 1), 'Marchand'), ((3, 2), 'Orcs'), ((3, 3), 'Faim'), ((3, 4), 'Lézard géant'),
                ((3, 5), 'Coup de soleil'),
                ((3, 6), 'Mésaventure'),
                ((4, 1), 'Bandits'), ((4, 2), 'Epeiste'), ((4, 3), 'Faim'), ((4, 4), 'Serpent'),
                ((4, 5), 'Coup de soleil'),
                ((4, 6), 'Mésaventure'),
                ((5, 1), 'Magicien'), ((5, 2), 'Mercenaires'), ((5, 3), 'Mines abandonnées'), ((5, 4), 'Serpent'),
                ((5, 5), 'Coup de soleil'),
                ((5, 6), 'Mort de la monture'),
                ((6, 1), 'Maison de magicien'), ((6, 2), 'Cave'), ((6, 3), 'Temple secret'),
                ((6, 4), 'Faim'), ((6, 5), 'Plantes empoisonées'),
                ((6, 6), 'Mort de la monture')]

event_forest = [((1, 1), 'Epeiste'), ((1, 2), 'Araignées'), ((1, 3), 'Elfes'), ((1, 4), 'Attaque de sanglier'),
                ((1, 5), 'Ville d\'elfe'),
                ((1, 6), 'Mésaventure'),
                ((2, 1), 'Mercenaires'), ((2, 2), 'Araignées'), ((2, 3), 'Elfes'), ((2, 4), 'Attaque de sanglier'),
                ((2, 5), 'Forteresse d\'elfe'),
                ((2, 6), 'Mésaventure'),
                ((3, 1), 'Amazones'), ((3, 2), 'Sorcière'), ((3, 3), 'Gobelins'), ((3, 4), 'Ours'),
                ((3, 5), 'Ville cachée'),
                ((3, 6), 'Mésaventure'),
                ((4, 1), 'Nain'), ((4, 2), 'Ferme'), ((4, 3), 'Spectre'), ((4, 4), 'Ours'),
                ((4, 5), 'Ruines'),
                ((4, 6), 'Mésaventure'),
                ((5, 1), 'Elfe'), ((5, 2), 'Bandits'), ((5, 3), 'Lutins'), ((5, 4), 'Chat de chasse'),
                ((5, 5), 'Bois infranchissable'),
                ((5, 6), 'Pluie'),
                ((6, 1), 'Semi-Homme'), ((6, 2), 'Marchand'), ((6, 3), 'Lutins'),
                ((6, 4), 'Loups'), ((6, 5), 'Bois infranchissable'),
                ((6, 6), 'Pluie')]

event_farm = [((1, 1), 'Ferme'), ((1, 2), 'Prêtre'), ((1, 3), 'Epeiste'), ((1, 4), 'Marchand'),
              ((1, 5), 'Menestrel itinérant'),
              ((1, 6), 'Mésaventure'),
              ((2, 1), 'Ferme'), ((2, 2), 'Prêtre'), ((2, 3), 'Mercenaires'), ((2, 4), 'Marchand'),
              ((2, 5), 'Menestrel itinérant'),
              ((2, 6), 'Mésaventure'),
              ((3, 1), 'Ferme'), ((3, 2), 'Moines'), ((3, 3), 'Amazones'), ((3, 4), 'Marchand'),
              ((3, 5), 'Fantômes'),
              ((3, 6), 'Pluie'),
              ((4, 1), 'Ferme'), ((4, 2), 'Moines'), ((4, 3), 'Nain'), ((4, 4), 'Marchand'),
              ((4, 5), 'Patrouille montée'),
              ((4, 6), 'Pluie'),
              ((5, 1), 'Ferme'), ((5, 2), 'Magicien'), ((5, 3), 'Elfe'), ((5, 4), 'Caravane de marchand'),
              ((5, 5), 'Police locale'),
              ((5, 6), 'Ferme'),
              ((6, 1), 'Ferme'), ((6, 2), 'Rencontre avec un seigneur'), ((6, 3), 'Semi-Homme'),
              ((6, 4), 'Poursuite avec un paysan'), ((6, 5), 'Police locale'),
              ((6, 6), 'Ferme')]

event_hills = [((1, 1), 'Epeiste'), ((1, 2), 'Dragon'), ((1, 3), 'Cave'), ((1, 4), 'Chat de chasse'),
               ((1, 5), 'Géant'),
               ((1, 6), 'Mésaventure'),
               ((2, 1), 'Mercenaires'), ((2, 2), 'Petite tempête'), ((2, 3), 'Cave'), ((2, 4), 'Chat de chasse'),
               ((2, 5), 'Gobelins'),
               ((2, 6), 'Mésaventure'),
               ((3, 1), 'Amazones'), ((3, 2), 'Magicien'), ((3, 3), 'Nains'), ((3, 4), 'Chat de chasse'),
               ((3, 5), 'Mines de nain'),
               ((3, 6), 'Mésaventure'),
               ((4, 1), 'Nain'), ((4, 2), 'Bandits'), ((4, 3), 'Ville de semi-homme'), ((4, 4), 'Loups'),
               ((4, 5), 'Mines abandonnées'),
               ((4, 6), 'Passage étroit'),
               ((5, 1), 'Efle'), ((5, 2), 'Maison de magicien'), ((5, 3), 'Orcs'), ((5, 4), 'Marchand'),
               ((5, 5), 'Temple secret'),
               ((5, 6), 'Pluie'),
               ((6, 1), 'Semi-Homme'), ((6, 2), 'Moines'), ((6, 3), 'Tour orc'),
               ((6, 4), 'Marchand'), ((6, 5), 'Ruines'),
               ((6, 6), 'Pluie')]

event_swamp = [((1, 1), 'Epeiste'), ((1, 2), 'Moines'), ((1, 3), 'Spectre'), ((1, 4), 'Serpent'),
               ((1, 5), 'Marécage infranchissable'),
               ((1, 6), 'Mésaventure'),
               ((2, 1), 'Mercenaires'), ((2, 2), 'Ferme'), ((2, 3), 'Spectre'), ((2, 4), 'Serpent'),
               ((2, 5), 'Marécage infranchissable'),
               ((2, 6), 'Mésaventure'),
               ((3, 1), 'Amazones'), ((3, 2), 'Sorcière'), ((3, 3), 'Lézard géant'), ((3, 4), 'Crocodiles'),
               ((3, 5), 'Marécage infranchissable'),
               ((3, 6), 'Mésaventure'),
               ((4, 1), 'Nain'), ((4, 2), 'Bandits'), ((4, 3), 'Gobelins'), ((4, 4), 'Crocodiles'),
               ((4, 5), 'Sables mouvants'),
               ((4, 6), 'Montures en péril'),
               ((5, 1), 'Elfe'), ((5, 2), 'Bandits'), ((5, 3), 'Troll'), ((5, 4), 'Marée'),
               ((5, 5), 'Ruines'),
               ((5, 6), 'Montures en péril'),
               ((6, 1), 'Semi-Homme'), ((6, 2), 'Araignées'), ((6, 3), 'Dragon'),
               ((6, 4), 'Marée'), ((6, 5), 'Plantes empoisonées'),
               ((6, 6), 'Pourriture')]
